### ISSUE TITLE
Shieldcore incdicator number offset.

### ISSUE THREAD

**Issue by DizzyLove** [Gay-Snake-Squad/Ted-Tweaks#2]
![Shieldcore indicator](https://user-images.githubusercontent.com/61663825/208201608-92eb4256-a07d-46cf-9f60-52d004e05a2c.png)

The shieldcore incdicator number offsets too much to the right side of the screen using 3840x2160 pixel scaling in GZDoom, causing some unwanted overlapping with the inventory display.

**Comment by tedthedragon** [comment]
Should be fixed as of most recent commit, will keep this open until I am certain though.
May now conflict with the weapon sprite on full hud though that's easy enough to fix.

**Comment by DizzyLove** [comment]
💜
